# Generated by Django 5.2.1 on 2025-06-10 19:53

import sceneviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to=sceneviewer.models.user_directory_path)),
                ('image_file', models.ImageField(upload_to=sceneviewer.models.user_directory_path)),
            ],
        ),
    ]
