# Generated by Django 5.2.1 on 2025-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_360',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
