# Generated by Django 5.2.1 on 2025-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0002_scene_is_360'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='latitude',
            field=models.FloatField(default=60.73958103204708),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='longitude',
            field=models.FloatField(default=24.75605680821921),
            preserve_default=False,
        ),
    ]
