# Generated by Django 5.2.1 on 2025-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0003_scene_latitude_scene_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='latitude',
            field=models.FloatField(default=60.73958103204708),
        ),
        migrations.AlterField(
            model_name='scene',
            name='longitude',
            field=models.FloatField(default=24.75605680821921),
        ),
    ]
