# Generated by Django 5.2.1 on 2025-07-23 10:54

import sceneviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0004_alter_scene_latitude_alter_scene_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=sceneviewer.models.thumbnail_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scene',
            name='image_file',
            field=models.ImageField(upload_to=sceneviewer.models.image_directory_path),
        ),
    ]
