# Generated by Django 5.2.2 on 2025-07-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorite_cat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme_color",
            field=models.CharField(default="#1a1a1a", max_length=7),
        ),
    ]
