# Generated by Django 5.2.2 on 2025-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_favorite_cat_profile_theme_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_backgrounds/"
            ),
        ),
    ]
