# Generated by Django 5.2.1 on 2025-07-06 21:42

import django.db.models.deletion
import userposts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('text_content', models.TextField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=userposts.models.user_directory_path)),
                ('active', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('linked_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userposts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('title__isnull', True), ('linked_post__isnull', True), _connector='XOR'), name='post-title-constraint'), models.CheckConstraint(condition=models.Q(('text_content__isnull', False), ('image_file__isnull', False), _connector='OR'), name='post-content-constraint')],
            },
        ),
    ]
