# Generated by Django 5.2.1 on 2025-07-28 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0005_scene_thumbnail_alter_scene_image_file'),
        ('userposts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='post-content-constraint',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('text_content__exact', ''), _negated=True), name='post-content-constraint'),
        ),
    ]
