# Generated by Django 5.2.1 on 2025-07-28 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneviewer', '0005_scene_thumbnail_alter_scene_image_file'),
        ('userposts', '0002_remove_post_post_content_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('title__exact', ''), _negated=True), ('linked_post__isnull', False), _connector='XOR'), models.Q(('linked_post__isnull', False), ('linked_scene__isnull', False), _connector='XOR'), _connector='OR'), name='post-title-comment-constraint'),
        ),
    ]
